import type { Question } from "./types"

export const QUESTIONS: Question[] = [
  {
    id: "goal",
    nodeLabel: "Goal",
    title: "What are you trying to do?",
    subtitle: "Pick the closest match.",
    kind: "single",
    why: "This is the strongest signal. It usually determines which family of approaches is even on the table.",
    options: [
      { value: "predict", label: "Predict a number or outcome", hint: "Forecasting, regression, risk scoring" },
      { value: "classify", label: "Classify or sort things into buckets", hint: "Spam detection, topic tagging, triage" },
      { value: "cluster", label: "Find groups or structure in data", hint: "Segmentation, pattern discovery" },
      { value: "retrieve", label: "Find or rank relevant items", hint: "Search, recommendation, ranking" },
      { value: "generate", label: "Generate text, images, or media", hint: "Drafting, summarization, creative output" },
      { value: "extract", label: "Pull structure out of messy input", hint: "Parse documents, pull fields, normalize" },
      { value: "automate", label: "Automate a multi-step task", hint: "Workflows, routing, tool use" },
      { value: "explore", label: "Explore data to understand it", hint: "Analytics, EDA, hypothesis testing" },
    ],
  },
  {
    id: "necessity",
    nodeLabel: "Need AI?",
    title: "Would rules or analytics actually solve this?",
    subtitle: "Be honest. A simpler system is almost always better if it works.",
    kind: "single",
    why: "A lot of real projects don't need ML. If rules, SQL, or a lookup table would do it, that's the right answer — not the boring one.",
    options: [
      { value: "rules-fine", label: "Rules would probably work fine" },
      { value: "rules-maybe", label: "Rules could work but feel fragile" },
      { value: "unsure", label: "Not sure — that's why I'm here" },
      { value: "needs-learning", label: "The pattern is too complex for rules" },
      { value: "needs-reasoning", label: "It needs language understanding or reasoning" },
    ],
  },
  {
    id: "modality",
    nodeLabel: "Input",
    title: "What does your input look like?",
    subtitle: "This determines which existing models you can reuse.",
    kind: "single",
    why: "Modality determines whether you can stand on a pretrained model or have to build more from scratch.",
    options: [
      { value: "tabular", label: "Tables or structured data" },
      { value: "text", label: "Text or documents" },
      { value: "image", label: "Images" },
      { value: "audio", label: "Audio or speech" },
      { value: "video", label: "Video" },
      { value: "code", label: "Source code" },
      { value: "multimodal", label: "A mix of the above" },
    ],
  },
  {
    id: "data",
    nodeLabel: "Data",
    title: "How ready is your data?",
    subtitle: "This is usually the real bottleneck.",
    kind: "single",
    why: "Your data situation decides whether you train, fine-tune, prompt, or spend the next few months fixing your pipeline first.",
    options: [
      { value: "clean-labeled", label: "Clean and well labeled" },
      { value: "clean-unlabeled", label: "Clean but not labeled" },
      { value: "messy", label: "Messy or fragmented" },
      { value: "sparse", label: "Not much data yet" },
      { value: "sensitive", label: "Sensitive or regulated" },
      { value: "live", label: "Streaming or live" },
    ],
  },
  {
    id: "labels",
    nodeLabel: "Labels",
    title: "Do you have labeled training examples?",
    subtitle: "This determines which learning strategies are available.",
    kind: "single",
    why: "No labels and no realistic path to getting them rules out most supervised approaches before you even start.",
    options: [
      { value: "have", label: "Yes, and they're reliable" },
      { value: "noisy", label: "Yes, but they're noisy" },
      { value: "can-label", label: "I can create them with effort" },
      { value: "weak", label: "Only weak or indirect signals" },
      { value: "none", label: "No labels and no clear way to get them" },
    ],
  },
  {
    id: "constraints",
    nodeLabel: "Limits",
    title: "What are your hard limits?",
    subtitle: "Select everything that applies.",
    kind: "multi",
    why: "Constraints usually knock out the obvious-looking answer before you start. Check these first.",
    options: [
      { value: "privacy", label: "Data can't leave our systems", hint: "On-prem only, no third-party APIs" },
      { value: "interpretability", label: "The decision has to be explainable" },
      { value: "low-latency", label: "Response time is critical" },
      { value: "low-compute", label: "Limited compute or tight budget" },
      { value: "high-stakes", label: "Errors are expensive or dangerous" },
      { value: "none", label: "No hard constraints yet" },
    ],
  },
  {
    id: "system",
    nodeLabel: "System",
    title: "What else does the system need to do?",
    subtitle: "Select everything that applies.",
    kind: "multi",
    why: "Whether you need retrieval, tools, or live data determines if a single model call is enough — or if you need something bigger.",
    options: [
      { value: "knowledge", label: "Answers must come from a specific knowledge base" },
      { value: "fresh", label: "Needs live or frequently updated data" },
      { value: "tools", label: "Has to call external tools or APIs" },
      { value: "human-loop", label: "Humans review or correct outputs" },
      { value: "model-only", label: "A single model output is enough" },
    ],
  },
  {
    id: "stage",
    nodeLabel: "Stage",
    title: "Where are you in the project?",
    subtitle: "This calibrates how much risk and effort makes sense.",
    kind: "single",
    why: "A class project and a production system should not start the same way. The right approach depends on stakes and resources.",
    options: [
      { value: "learning", label: "Learning or exploring" },
      { value: "prototype", label: "Building a prototype or demo" },
      { value: "research", label: "Research or publication" },
      { value: "production", label: "Heading to production" },
    ],
  },
]

export const QUESTION_BY_ID: Record<string, Question> = Object.fromEntries(
  QUESTIONS.map((q) => [q.id, q]),
)
